# Generated by Django 5.1.7 on 2025-04-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('crop_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='ImageUpload',
        ),
    ]
