# Generated by Django 5.1.7 on 2025-04-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_uploadedimage_delete_imageupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='crop_type',
            field=models.CharField(max_length=200),
        ),
    ]
