# Generated by Django 5.0.7 on 2024-07-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_section_alter_student_roll_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('teacher_class', models.IntegerField()),
                ('subject', models.CharField(max_length=20)),
                ('ph_number', models.IntegerField(max_length=11)),
            ],
        ),
    ]
