# Generated by Django 5.0.7 on 2024-07-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='ph_number',
            field=models.IntegerField(max_length=13),
        ),
    ]
