# Generated by Django 5.1.7 on 2025-05-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
