# Generated by Django 5.0.7 on 2024-09-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_grade_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='section',
            field=models.CharField(default='A', max_length=5),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
