# Generated by Django 5.0.7 on 2024-07-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_teacher_ph_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='ph_number',
            field=models.IntegerField(),
        ),
    ]
